name: Close PRs from Forks

on:
  pull_request_target:
    types: [opened]

jobs:
  check-pr-origin:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from a fork
        id: check-fork
        run: |
          # Extract forks URLs and check if the pull request is from a fork
          BASE_REPO_FORKS_URL="${{ github.event.pull_request.base.repo.forks_url }}"
          HEAD_REPO_FORKS_URL="${{ github.event.pull_request.head.repo.forks_url }}"
          
          echo "Base repository forks URL: $BASE_REPO_FORKS_URL"
          echo "Head repository forks URL: $HEAD_REPO_FORKS_URL"

          # Compare the forks URL of both repositories
          if [[ "$BASE_REPO_FORKS_URL" != "$HEAD_REPO_FORKS_URL" ]]; then
            echo "PR is from a fork"
            echo "true" >> $GITHUB_ENV
          else
            echo "PR is from the same repository"
            echo "false" >> $GITHUB_ENV
          fi

      - name: Close PR if from a fork
        if: env.PR_IS_FORK == 'true'
        run: |
          echo "Closing the pull request because it's from a forked repository."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"body": "Closing this pull request because it is from a forked repository.", "event": "REQUEST_CHANGES"}'

      - name: Close the pull request
        if: env.PR_IS_FORK == 'true'
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            -d '{"state": "closed"}'
