name: Close PRs from Forks

on:
  pull_request:
    types: [opened]

jobs:
  check-pr-origin:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from a fork
        id: check-fork
        run: |
          # Extract repository IDs and check if the pull request is from a fork
          BASE_REPO_ID="${{ github.event.pull_request.base.repo.id }}"
          HEAD_REPO_ID="${{ github.event.pull_request.head.repo.id }}"
          
          echo "Base repository ID: $BASE_REPO_ID"
          echo "Head repository ID: $HEAD_REPO_ID"

          if [[ "$BASE_REPO_ID" != "$HEAD_REPO_ID" ]]; then
            echo "PR is from a fork"
            echo "true" > is_fork.txt
          else
            echo "PR is from the same repository"
            echo "false" > is_fork.txt
          fi

      - name: Close PR if from a fork
        if: ${{ steps.check-fork.outputs.is_fork == 'true' }}
        run: |
          echo "Closing the pull request because it's from a forked repository."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"body": "Closing this pull request because it is from a forked repository.", "event": "REQUEST_CHANGES"}'

      - name: Close the pull request
        if: ${{ steps.check-fork.outputs.is_fork == 'true' }}
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            -d '{"state": "closed"}'
