name: Check PR Source

on:
  pull_request_target:
    types: [opened]

jobs:
  check-pr-source:
    runs-on: ubuntu-latest

    steps:
      - name: Print PR source details
        run: |
          echo "Pull Request Source:"
          echo "Base repository: ${{ github.event.pull_request.base.repo.full_name }}"
          echo "Base repository owner: ${{ github.event.pull_request.base.repo.owner.login }}"
          echo "Base branch: ${{ github.event.pull_request.base.ref }}"
          
          echo "Head repository: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Head repository owner: ${{ github.event.pull_request.head.repo.owner.login }}"
          echo "Head branch: ${{ github.event.pull_request.head.ref }}"

      - name: Check if PR is from a fork
        id: check-fork
        run: |
          HEAD_REPO_OWNER="${{ github.event.pull_request.head.repo.owner.login }}"
          BASE_REPO_OWNER="${{ github.event.pull_request.base.repo.owner.login }}"

          if [[ "$HEAD_REPO_OWNER" != "$BASE_REPO_OWNER" ]]; then
            echo "PR is from a fork."
            echo "true" >> $GITHUB_ENV
          else
            echo "PR is from the same repository."
            echo "false" >> $GITHUB_ENV

      - name: Conditional action if from fork
        if: env.PR_IS_FORK == 'true'
        run: |
          echo "This pull request is from a forked repository."
